//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Entry_App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Data_Entry_App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete_Button_Text {
            get {
                return ResourceManager.GetString("Delete_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Details Deleted Successfully.
        /// </summary>
        internal static string Delete_Successful_Message {
            get {
                return ResourceManager.GetString("Delete_Successful_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Successful.
        /// </summary>
        internal static string Delete_Successful_Message_Title {
            get {
                return ResourceManager.GetString("Delete_Successful_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the following..
        /// </summary>
        internal static string Error_Message_Header {
            get {
                return ResourceManager.GetString("Error_Message_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export_Button_Text {
            get {
                return ResourceManager.GetString("Export_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Login_Clear_Button_Text {
            get {
                return ResourceManager.GetString("Login_Clear_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login_Login_Button_Text {
            get {
                return ResourceManager.GetString("Login_Login_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password :.
        /// </summary>
        internal static string Login_Password_Lable_Text {
            get {
                return ResourceManager.GetString("Login_Password_Lable_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name :.
        /// </summary>
        internal static string Login_Username_Label_Text {
            get {
                return ResourceManager.GetString("Login_Username_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter a valid Username or Password.
        /// </summary>
        internal static string Login_Validation_Message {
            get {
                return ResourceManager.GetString("Login_Validation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login - Message.
        /// </summary>
        internal static string Login_Validation_Message_Title {
            get {
                return ResourceManager.GetString("Login_Validation_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print_Print_Button_Text {
            get {
                return ResourceManager.GetString("Print_Print_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Preview.
        /// </summary>
        internal static string Print_PrintPreview_Button_Text {
            get {
                return ResourceManager.GetString("Print_PrintPreview_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        internal static string Registration_DateOfBirth_Label_Text {
            get {
                return ResourceManager.GetString("Registration_DateOfBirth_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed.
        /// </summary>
        internal static string Registration_Error_Message {
            get {
                return ResourceManager.GetString("Registration_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration error.
        /// </summary>
        internal static string Registration_Error_Message_Title {
            get {
                return ResourceManager.GetString("Registration_Error_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health status.
        /// </summary>
        internal static string Registration_HealthStatus_Label_Text {
            get {
                return ResourceManager.GetString("Registration_HealthStatus_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select health status..
        /// </summary>
        internal static string Registration_HealthStatus_Select_Text {
            get {
                return ResourceManager.GetString("Registration_HealthStatus_Select_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital status.
        /// </summary>
        internal static string Registration_MaritalStatus_Label_Text {
            get {
                return ResourceManager.GetString("Registration_MaritalStatus_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select marital status..
        /// </summary>
        internal static string Registration_MaritalStatus_Select_Text {
            get {
                return ResourceManager.GetString("Registration_MaritalStatus_Select_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Registration_Name_Label_Text {
            get {
                return ResourceManager.GetString("Registration_Name_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        internal static string Registration_Name_Required_Text {
            get {
                return ResourceManager.GetString("Registration_Name_Required_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Registration_Register_Button_Text {
            get {
                return ResourceManager.GetString("Registration_Register_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Registration_Role_Label_Text {
            get {
                return ResourceManager.GetString("Registration_Role_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a User Role.
        /// </summary>
        internal static string Registration_Role_Select_Text {
            get {
                return ResourceManager.GetString("Registration_Role_Select_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        internal static string Registration_Salary_Label_Text {
            get {
                return ResourceManager.GetString("Registration_Salary_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New member registered successfully!.
        /// </summary>
        internal static string Registration_Successful_Message {
            get {
                return ResourceManager.GetString("Registration_Successful_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Successful.
        /// </summary>
        internal static string Registration_Successful_Message_Title {
            get {
                return ResourceManager.GetString("Registration_Successful_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Member Club - Members.
        /// </summary>
        internal static string Report_Header {
            get {
                return ResourceManager.GetString("Report_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Search_Refresh_Button_Text {
            get {
                return ResourceManager.GetString("Search_Refresh_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search_Search_Button_Text {
            get {
                return ResourceManager.GetString("Search_Search_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! System error. Please contact administrator..
        /// </summary>
        internal static string System_Error_Message {
            get {
                return ResourceManager.GetString("System_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - Message.
        /// </summary>
        internal static string System_Error_Message_Title {
            get {
                return ResourceManager.GetString("System_Error_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update_Button_Text {
            get {
                return ResourceManager.GetString("Update_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update error.
        /// </summary>
        internal static string Update_Error_Message_Title {
            get {
                return ResourceManager.GetString("Update_Error_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member details updated successfully.
        /// </summary>
        internal static string Update_Successful_Message {
            get {
                return ResourceManager.GetString("Update_Successful_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update successfull.
        /// </summary>
        internal static string Update_Successful_Message_Title {
            get {
                return ResourceManager.GetString("Update_Successful_Message_Title", resourceCulture);
            }
        }
    }
}
